name: Build

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Set up
        uses: docker/setup-buildx-action@v2
      - name: Build with Retry
        uses: Wandalen/wretry.action@v1.0.36_js_action
        with:
          action: docker/build-push-action@v3
          with: |
            context: ./
            file: ./Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: ouwyukha/hello-world:latest
            provenance: false
            sbom: false
            no-cache: true
          attempt_limit: 3
      - name: Echo
        run: "echo 'Echo'"