name: Build with Manual Retry

on:
  workflow_dispatch:

jobs:
  build:
    name: Build with Manual Retry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Set up
        uses: docker/setup-buildx-action@v2
      - name: Build Attempt 1/3
        id: buildnpush1
        continue-on-error: true
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ouwyukha/hello-world:latest
          provenance: false
          sbom: false
          no-cache: true
      - name: Build Attempt 2/3
        id: buildnpush2
        if: steps.buildnpush1.outcome == 'failure'
        continue-on-error: true
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ouwyukha/hello-world:latest
          provenance: false
          sbom: false
          no-cache: true
      - name: Build Attempt 3/3
        id: buildnpush3
        if: steps.buildnpush2.outcome == 'failure'
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ouwyukha/hello-world:latest
          provenance: false
          sbom: false
          no-cache: true
      - name: Echo
        run: "echo 'Echo'"